spring:
  profiles:
    active: 
    - dev
---
spring:
  profiles: dev
  applications: 
     name: microservicecloud-config-atguigu-dev
---
spring:
  profiles: test
  applications: 
     name: microservicecloud-config-atguigu-test
